// definitions for Alpha sign data files

#define	TXT_MSG1	'1'
#define	TXT_MSG2	'2'
#define	TXT_STK1	'A'
#define	TXT_STK2	'B'
#define	TXT_STK3	'C'
#define	TXT_STK4	'D'
#define	TXT_STK5	'E'
#define	TXT_STK6	'F'
#define	TXT_STK7	'G'
#define	TXT_STK8	'H'
#define	DOT_G18		'A'
#define	DOT_G14		'B'
#define	DOT_G38		'C'
#define	DOT_G12		'D'
#define	DOT_G58		'E'
#define	DOT_G34		'F'
#define	DOT_G78		'G'
#define	DOT_R18		'a'
#define	DOT_R14		'b'
#define	DOT_R38		'c'
#define	DOT_R12		'd'
#define	DOT_R58		'e'
#define	DOT_R34		'f'
#define	DOT_R78		'g'

extern char *dots1r[];	// 1/8 red
extern char *dots2r[];	// 1/4 red
extern char *dots3r[];	// 3/8 red
extern char *dots4r[];	// 1/2 red
extern char *dots5r[];	// 5/8 red
extern char *dots6r[];	// 3/4 red
extern char *dots7r[];	// 7/8 red
extern char *dots1g[];	// 1/8 green
extern char *dots2g[];	// 1/4 green
extern char *dots3g[];	// 3/8 green
extern char *dots4g[];	// 1/2 green
extern char *dots5g[];	// 5/8 green
extern char *dots6g[];	// 3/4 green
extern char *dots7g[];	// 7/8 green

