// definitions for Alpha sign data files

#define	TXT_MSG1	'1'
#define	DOT_JA1		'A'
#define	DOT_JA6		'B'
#define	DOT_JA8		'C'
#define	DOT_JAA		'D'
#define	DOT_JB1		'E'
#define	DOT_JB2		'F'
#define	DOT_JB3		'G'
#define	DOT_JB5		'H'
#define	DOT_JB8		'I'
#define	DOT_JBA		'J'
#define	DOT_JBB		'K'
#define	DOT_JBC		'L'
#define	DOT_JBF		'M'
#define	DOT_JC0		'N'
#define	DOT_JC3		'O'
#define	DOT_JC4		'P'
#define	DOT_JCD		'Q'
#define	DOT_JD2		'R'
#define	DOT_JD6		'S'
#define	DOT_JD7		'T'
#define	DOT_JD8		'U'
#define	DOT_JDD		'V'
#define	DOT_JDE		'W'

extern char *dotsA1[];
extern char *dotsA6[];
extern char *dotsA8[];
extern char *dotsAA[];
extern char *dotsB1[];
extern char *dotsB2[];
extern char *dotsB3[];
extern char *dotsB5[];
extern char *dotsB8[];
extern char *dotsBA[];
extern char *dotsBB[];
extern char *dotsBC[];
extern char *dotsBF[];
extern char *dotsC0[];
extern char *dotsC3[];
extern char *dotsC4[];
extern char *dotsCD[];
extern char *dotsD2[];
extern char *dotsD6[];
extern char *dotsD7[];
extern char *dotsD8[];
extern char *dotsDD[];
extern char *dotsDE[];

